# Generated by Django 4.2.3 on 2023-07-30 05:29

import ads.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0008_alter_car_year'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='owner',
            name='city',
        ),
        migrations.RemoveField(
            model_name='owner',
            name='country',
        ),
        migrations.AddField(
            model_name='ad',
            name='city',
            field=models.CharField(default='Ufa', max_length=50),
        ),
        migrations.AddField(
            model_name='ad',
            name='country',
            field=models.CharField(default='Russia', max_length=50),
        ),
        migrations.AlterField(
            model_name='ad',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=9, validators=[django.core.validators.MinValueValidator(1, 'The rental price should be greater than zero.')]),
        ),
        migrations.AlterField(
            model_name='car',
            name='year',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1980), ads.models.max_value_current_year], verbose_name=('year',)),
        ),
    ]
