# Generated by Django 4.2.3 on 2023-07-30 11:08

import ads.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0011_ad_price_per_alter_car_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='price_per',
            field=models.CharField(choices=[('H', 'hour'), ('D', 'day'), ('W', 'week'), ('M', 'month')], default='H', max_length=1),
        ),
        migrations.AlterField(
            model_name='car',
            name='year',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1980), ads.models.max_value_current_year], verbose_name=('year',)),
        ),
    ]
