# Generated by Django 4.2.3 on 2023-08-02 07:37

import ads.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0018_alter_car_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='price_per',
            field=models.CharField(choices=[('Hour', 'hour'), ('Day', 'day'), ('Week', 'week'), ('Month', 'month')], default='H', max_length=5),
        ),
        migrations.AlterField(
            model_name='car',
            name='transmission',
            field=models.CharField(choices=[('Automatic', 'Automatic'), ('Manual', 'Manual')], max_length=9),
        ),
        migrations.AlterField(
            model_name='car',
            name='year',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1980), ads.models.max_value_current_year], verbose_name=('year',)),
        ),
    ]
