# Generated by Django 4.2.3 on 2023-08-04 13:03

import ads.models
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0026_alter_car_year'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ad',
            name='phone',
        ),
        migrations.AlterField(
            model_name='ad',
            name='car',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ads.car'),
        ),
        migrations.AlterField(
            model_name='car',
            name='year',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1980), ads.models.max_value_current_year], verbose_name=('year',)),
        ),
    ]
